# Generated by Django 3.2.10 on 2022-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_image/avatar.jpg', null=True, upload_to='user_image/'),
        ),
    ]
