# Generated by Django 3.2.10 on 2022-01-11 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only. At least One letter is necessary', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='username must contain at least one letter; @ is not accepted', regex='^[\\w.+-]*[a-zA-Z][\\w.+-]*\\Z')], verbose_name='username'),
        ),
    ]
