# Generated by Django 3.2.10 on 2022-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Phone_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the phone verified.', verbose_name='phone status'),
        ),
    ]
