# Generated by Django 3.2.10 on 2022-01-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_Phone_verified',
            new_name='is_phone_verified',
        ),
    ]
